apiVersion: v1
kind: Service
metadata:
  name: microservice-demo-one
  namespace: micro-one
  labels: 
    app: micro-one-app
    version: v1
spec:
  type: NodePort
  ports:
    - port: 8089
  selector:
    app: micro-one-app