resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/component: exporter
  app.kubernetes.io/name: blackbox-exporter
  
commonAnnotations:
  prometheus.io/scrape: 'true'
  prometheus.io/port: '9115'
