kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: "key-to-share-1.2.3.4"
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
