resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app: prometheus-server

commonAnnotations:
  prometheus.io/scrape: 'true'
  prometheus.io/port: '9090'
  metallb.universe.tf/allow-shared-ip: "key-to-share-1.2.3.4"