apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector:
    app: minio
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090